name: RasPi System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/raspi-system:latest
          ${{ secrets.DOCKER_USERNAME }}/raspi-system:${{ github.sha }}
    
    - name: Deploy to edge server
      if: github.ref == 'refs/heads/main'
      run: |
        ssh -i ${{ secrets.EDGE_SSH_KEY }} -o StrictHostKeyChecking=no \
          ${{ secrets.EDGE_USER }}@${{ secrets.EDGE_HOST }} \
          "docker pull ${{ secrets.DOCKER_USERNAME }}/raspi-system:latest && \
           docker stop raspi-system || true && \
           docker rm raspi-system || true && \
           docker run -d --name raspi-system --restart unless-stopped \
           ${{ secrets.DOCKER_USERNAME }}/raspi-system:latest" 